#!/bin/bash

echo "running lock from: $1" >> /tmp/lock

# Prevent multiple lock screens
[[ -z "$(pgrep i3lock)" ]] || exit

# Suspend notifications
killall -SIGUSR1 dunst

echo "no lock found, launching.." >> /tmp/lock

# Lock the screen
i3lock \
  --nofork \
  -i $(find /home/drake/images/wallpapers/lock/ -name "*" | shuf -n1) \
  --timepos="82:h-80" \
  --datepos="tx+24:ty+25" \
  --clock --datestr "Type password to unlock..." \
  --insidecolor=00000000 --ringcolor=ffffffff --line-uses-inside \
  --keyhlcolor=d23c3dff --bshlcolor=d23c3dff --separatorcolor=00000000 \
  --insidevercolor=fecf4dff --insidewrongcolor=d23c3dff \
  --ringvercolor=ffffffff --ringwrongcolor=ffffffff --indpos="x+230:h-75" \
  --radius=20 --ring-width=3 --veriftext="" --wrongtext="" \
  --verifcolor="ffffffff" --wrongcolor="ffffffff" --layoutcolor="ffffffff" --timecolor="ffffffff" --datecolor="ffffffff"

# Resume notifications
killall -SIGUSR2 dunst
