[keybindings]
"+" = ""
"." = ""
"<" = ""
">" = ""
"A" = ""
"Backspace" = "Back"
"Ctrl+a" = ""
"Ctrl+e" = ""
"Ctrl+n" = ""
"Ctrl+p" = ""
"Ctrl+s" = ""
"End" = ""
"F1" = ""
"F2" = ""
"F3" = ""
"Shift+Up" = ""
"Shift+Down" = ""
"Shift+b" = ""
"Shift+f" = ""
"Shift+o" = ""
"Shift+p" = ""
"Shift+s" = ""
"Shift+u" = ""
"b" = ""
"c" = ""
"d" = ""
"f" = ""
"o" = ""
"q" = ""
"s" = ""
"PageUp" = ""
"PageDown" = ""
"Up" = ""
"Down" = ""
"Left" = ""
"Right" = ""

"h" = "move left 1"
"j" = "move down 1"
"k" = "move up 1"
"l" = "move right 1"
"Shift+h" = "seek -10000"
"Shift+j" = "voldown"
"Shift+k" = "volup"
"Shift+l" = "seek +10000"

"n" = "next"
"Shift+n" = "previous"

"Shift+g" = "move top"
"gg" = "move gottom"

"Enter" = "play"
" " = "playpause" # Spacebar
"?" = "help"
"-" = "back"

"r" = "repeat"
"Shift+r" = "shuffle"

"Shift+q" = "quit"
"e" = "open current"
"Shift+e" = "open selected"

"/" = "focus search"
"e" = "focus library"
"b+0" = "focus queue"
"b+1" = "focus library"

"a" = "goto artist"
"Shift+a" = "goto album"

"Shift+y" = "share current"
"Shift+d" = "share selected"
